name: MainPipeline
on: 
  push:
    branches:
      - main
#     paths:
#       - 'backend/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v6
      - name: login to ACR
        uses: azure/docker-login@v2
        with: 
          registryname: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{secrets.ACR_USER_NAME}}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Push images to ACR
        uses: docker/build-push-action@v7
        with: 
          context: ./backend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/quote-app-backend:${{ github.sha }}

    


