name: MainPipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to ACR
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/quote-app-backend:${{ github.sha }}

      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: v-rnoone/DevOps-Project-06
          token: ${{ secrets.MANIFEST_REPO_PAT }}
          path: manifests-repo

      - name: Update image tag in backend.yaml
        run: |
          cd manifests-repo/K8S
          sed -i "s|image:.*quote-app-backend:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/quote-app-backend:${{ github.sha }}|" backend.yaml
          echo "--- Verify sed worked ---"
          cat backend.yaml | grep image:

      - name: Commit and push updated manifest
        run: |
          cd manifests-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add K8S/backend.yaml
          git commit -m "ci: update backend image to ${{ github.sha }}"
          git push